# -*- coding: utf-8 -*-
"""Cas de test du cahier de recette SYGEP.

Chaque module : (code, titre, objectif, [cas]).
Chaque cas    : (id, test, compte, préconditions, [étapes], résultat attendu, priorité).
Priorités : C = Critique (bloquant), M = Majeur, m = Mineur.
Comptes : ADM admin@admin.com · DIR directeur@sygep.test · CPT comptable@sygep.test ·
SEC secondaire@sygep.test (CFP de Thiès) · MNT maintenance@sygep.test ·
INF infrastructures@sygep.test · MAT matieres@sygep.test · AGT agent@sygep.test (CFP de Thiès).
"""

COMPTES = {
    "ADM": ("admin@admin.com", "Super administrateur"),
    "DIR": ("directeur@sygep.test", "Directeur"),
    "CPT": ("comptable@sygep.test", "Comptable matière principal"),
    "SEC": ("secondaire@sygep.test", "Comptable matière secondaire (CFP de Thiès)"),
    "MNT": ("maintenance@sygep.test", "Responsable maintenance"),
    "INF": ("infrastructures@sygep.test", "Responsable infrastructures"),
    "MAT": ("matieres@sygep.test", "Administrateur des matières"),
    "AGT": ("agent@sygep.test", "Agent / demandeur (CFP de Thiès)"),
}

MODULES = []


def module(code, titre, objectif, cas):
    MODULES.append((code, titre, objectif, cas))


# --------------------------------------------------------------------------------------
module("AUT", "Connexion, comptes et sécurité d'accès",
       "Vérifier qui peut entrer, avec quels droits, et que l'accès est correctement protégé.", [
    ("AUT-01", "Connexion réussie", "ADM", "Compte actif et approuvé",
     ["Ouvrir /login", "Saisir admin@admin.com et le mot de passe", "Valider"],
     "Le tableau de bord s'affiche. Le nom « Admin » apparaît en haut à droite.", "C"),
    ("AUT-02", "Mot de passe erroné", "ADM", "—",
     ["Ouvrir /login", "Saisir un bon e-mail et un mauvais mot de passe", "Valider"],
     "Un message d'erreur s'affiche ; l'utilisateur reste sur la page de connexion.", "C"),
    ("AUT-03", "Compte non approuvé refusé", "ADM", "Un utilisateur créé SANS cocher « Approuvé »",
     ["Se connecter avec ce compte"],
     "La connexion est refusée avec un message indiquant que le compte doit être approuvé par un administrateur.", "C"),
    ("AUT-04", "Inscription libre", "—", "Page /register accessible",
     ["Ouvrir /register", "Créer un compte avec un nouvel e-mail", "Tenter de se connecter avec"],
     "Le compte est créé mais ne peut pas se connecter (non approuvé). Dans Utilisateurs, il porte le rôle « User ».", "C"),
    ("AUT-05", "Approuver un compte inscrit", "ADM", "Compte créé à l'étape AUT-04",
     ["Utilisateurs > modifier le compte", "Cocher « Approuvé » et enregistrer", "Se connecter avec ce compte"],
     "La connexion réussit. Le menu ne montre presque aucun module (droits très limités du rôle « User »).", "M"),
    ("AUT-06", "Déconnexion", "ADM", "Connecté",
     ["Cliquer « Déconnexion » en bas du menu", "Confirmer « Se déconnecter »"],
     "Retour à la page de connexion. Le bouton Précédent du navigateur ne rouvre pas l'espace de gestion.", "C"),
    ("AUT-07", "Page protégée sans connexion", "—", "Déconnecté",
     ["Saisir directement l'adresse /admin/assets"],
     "Redirection vers la page de connexion.", "C"),
    ("AUT-08", "Changer son mot de passe", "ADM", "Droit « profil » présent",
     ["Menu du compte > Profil", "Saisir l'ancien puis le nouveau mot de passe", "Se déconnecter et se reconnecter avec le nouveau"],
     "Le nouveau mot de passe est accepté ; l'ancien ne fonctionne plus.", "M"),
    ("AUT-09", "Mot de passe oublié", "—", "Courrier (MAIL_*) configuré",
     ["Sur /login, cliquer « mot de passe oublié »", "Saisir un e-mail existant"],
     "Un message de confirmation s'affiche et un courriel de réinitialisation est envoyé.", "m"),
    ("AUT-10", "Session de longue durée", "ADM", "Connecté",
     ["Laisser la page ouverte au-delà de la durée de session (120 min par défaut)", "Soumettre un formulaire"],
     "Un message de page expirée (419) s'affiche proprement ; recharger la page permet de continuer.", "m"),
])

module("USR", "Utilisateurs, rôles et droits",
       "Vérifier la gestion des comptes et le fait que chaque profil ne voit que ce qui le concerne.", [
    ("USR-01", "Créer un utilisateur valide", "ADM", "Un service existe",
     ["Utilisateurs > Ajouter", "Nom, e-mail unique, mot de passe, cocher « Approuvé », service, rôle « Agent / demandeur »", "Enregistrer"],
     "L'utilisateur apparaît dans la liste. Il peut se connecter.", "C"),
    ("USR-02", "E-mail déjà utilisé", "ADM", "Un utilisateur existe avec l'e-mail X",
     ["Créer un utilisateur avec le même e-mail X"],
     "Refus avec un message sous le champ E-mail.", "C"),
    ("USR-03", "Rôle local sans service", "ADM", "—",
     ["Créer un utilisateur avec le rôle « Comptable matière secondaire »", "Laisser le service vide", "Enregistrer"],
     "Refus : « Le service de rattachement est obligatoire pour ce rôle. »", "C"),
    ("USR-04", "Rôle local sans service (modification)", "ADM", "Un utilisateur au rôle « Agent / demandeur » avec service",
     ["Modifier l'utilisateur", "Vider le service", "Enregistrer"],
     "Refus avec le même message.", "M"),
    ("USR-05", "Aucun rôle", "ADM", "—",
     ["Créer un utilisateur sans choisir de rôle"],
     "Refus (au moins un rôle est obligatoire).", "M"),
    ("USR-06", "Champs obligatoires signalés", "ADM", "—",
     ["Ouvrir Utilisateurs > Ajouter"],
     "Nom, e-mail, mot de passe et rôles portent l'astérisque rouge.", "m"),
    ("USR-07", "Modifier le rôle d'un utilisateur", "ADM", "Utilisateur agent",
     ["Changer son rôle en « Comptable matière secondaire »", "Se connecter avec ce compte"],
     "Le menu et les droits correspondent au nouveau rôle.", "M"),
    ("USR-08", "La page Rôles s'affiche", "ADM", "—",
     ["Rôles et autorisations > Rôles", "Ouvrir un rôle (œil) puis sa modification"],
     "La liste montre pour chaque rôle sa description et ses droits par domaine ; la fiche et le formulaire s'affichent sans erreur. (Échoue si le fichier PermissionCatalog.php est absent : voir Guide 10.1.)", "C"),
    ("USR-09", "Modifier les droits d'un rôle", "ADM", "Un rôle de test avec le droit « supprimer les matières »",
     ["Retirer ce droit du rôle", "Se reconnecter avec un compte de ce rôle", "Ouvrir la liste des matières"],
     "L'icône de suppression n'apparaît plus.", "M"),
    ("USR-10", "Menu adapté au profil", "AGT", "Compte agent",
     ["Se connecter", "Observer le menu"],
     "Seuls les modules autorisés apparaissent (matières du service, demandes de maintenance…) ; pas de Rôles, Stock, Infrastructures, Projets.", "C"),
    ("USR-11", "Accès direct interdit", "AGT", "Compte agent",
     ["Saisir l'adresse /admin/users ou /admin/stock-items"],
     "Erreur 403 (accès interdit).", "C"),
    ("USR-12", "Directeur en lecture seule", "DIR", "—",
     ["Ouvrir Matières, Projets, Infrastructures"],
     "Aucun bouton « Ajouter », « Modifier » ni « Supprimer » n'est proposé.", "M"),
    ("USR-13", "Administrateur système hors données métier", "ADM", "Un compte avec le rôle « Administrateur système »",
     ["Se connecter avec ce compte", "Observer le menu"],
     "Seuls Rôles et autorisations (et services en lecture) sont accessibles ; pas les matières ni le stock.", "M"),
    ("USR-14", "Suppression d'un utilisateur", "ADM", "Un utilisateur de test",
     ["Supprimer l'utilisateur (icône corbeille)", "Confirmer"],
     "Il disparaît de la liste. Ses actions passées restent dans l'historique.", "m"),
])

module("REF", "Référentiels (services, catégories, emplacements, fournisseurs, bons)",
       "Vérifier les listes de choix et les bons d'acquisition.", [
    ("REF-01", "Créer un service", "CPT", "Seul le comptable principal (ou le super administrateur) crée des services",
     ["Gestion Matières > Services > Ajouter", "Nom : « Service test »", "Enregistrer"],
     "Le service apparaît dans la liste.", "C"),
    ("REF-02", "Service sans nom", "CPT", "—",
     ["Services > Ajouter", "Laisser le nom vide", "Enregistrer"],
     "Refus avec message sous le champ Nom.", "C"),
    ("REF-03", "Créer une catégorie", "MAT", "—",
     ["Catégories > Ajouter", "Nom : « Catégorie test »", "Enregistrer"],
     "La catégorie apparaît ; elle est proposée dans le formulaire des matières.", "C"),
    ("REF-04", "Créer un emplacement", "MAT", "—",
     ["Emplacements > Ajouter", "Nom : « Salle test »", "Enregistrer"],
     "L'emplacement apparaît ; il est proposé dans le formulaire des matières.", "C"),
    ("REF-05", "Statuts de matières en français", "MAT", "Base installée avec les seeders",
     ["Statuts des matières"],
     "Les cinq statuts existent : Disponible, Pas disponible, En panne, En réparation, Affecté.", "C"),
    ("REF-06", "Créer un fournisseur", "MAT", "—",
     ["Fournisseurs > Ajouter", "Nom et contact", "Enregistrer"],
     "Le fournisseur apparaît dans la liste.", "C"),
    ("REF-07", "Fournisseur sans contact", "MAT", "—",
     ["Fournisseurs > Ajouter", "Renseigner le nom seulement"],
     "Refus : le contact est obligatoire.", "M"),
    ("REF-08", "Créer un bon valide", "MAT", "—",
     ["Bons > Ajouter", "Date d'émission, organisation, référence de commande, destinataire, « Bon », date de livraison", "Enregistrer"],
     "Le bon apparaît dans la liste avec le nombre de matières à 0.", "C"),
    ("REF-09", "Référence de commande en double", "MAT", "Un bon avec la référence R1 existe",
     ["Créer un second bon avec la référence R1"],
     "Refus : la référence est déjà utilisée.", "C"),
    ("REF-10", "Même organisation, deux bons", "MAT", "Un bon de l'organisation O existe",
     ["Créer un bon de la même organisation O avec une autre référence"],
     "Accepté (une organisation peut avoir plusieurs bons).", "C"),
    ("REF-11", "Livraison avant émission", "MAT", "—",
     ["Créer un bon avec une date de livraison antérieure à la date d'émission"],
     "Refus avec message sous la date de livraison.", "M"),
    ("REF-12", "Bon sans libellé « Bon »", "MAT", "—",
     ["Créer un bon en laissant le champ « Bon » vide"],
     "Refus (champ obligatoire).", "M"),
    ("REF-13", "Fiche d'un bon : matières reçues", "MAT", "Une matière créée avec ce bon (voir MAT-01)",
     ["Bons > œil du bon concerné"],
     "La fiche liste les matières reçues (code, nom, catégorie, état). La liste des bons indique le bon nombre.", "M"),
    ("REF-14", "Modifier un bon", "MAT", "Un bon existe",
     ["Modifier la date de livraison", "Enregistrer"],
     "La modification est enregistrée ; les mêmes règles s'appliquent.", "m"),
])

module("AGT", "Agents", "Vérifier l'enregistrement des bénéficiaires du matériel.", [
    ("AGT-01", "Créer un agent valide", "MAT", "Un service existe",
     ["Agents > Ajouter", "Nom, prénom, téléphone, service", "Enregistrer"],
     "L'agent apparaît dans la liste avec son service.", "C"),
    ("AGT-02", "Champs obligatoires", "MAT", "—",
     ["Agents > Ajouter", "Laisser nom, prénom, téléphone et service vides", "Enregistrer"],
     "Refus ; chaque champ obligatoire affiche son message. Les libellés portent l'astérisque.", "C"),
    ("AGT-03", "E-mail invalide", "MAT", "—",
     ["Saisir « pas-un-mail » dans l'e-mail"],
     "Refus avec message sous le champ.", "M"),
    ("AGT-04", "E-mail facultatif et non unique", "MAT", "Un agent avec l'e-mail X existe",
     ["Créer un second agent avec le même e-mail X", "Créer un troisième sans e-mail"],
     "Les deux sont acceptés.", "m"),
    ("AGT-05", "Fiche d'un agent", "MAT", "Un agent détient du matériel (ex. Moussa Ndiaye)",
     ["Agents > œil"],
     "La fiche montre le matériel détenu et ses bons d'affectation en cours.", "M"),
    ("AGT-06", "Chiffres de la liste", "MAT", "Jeu de démonstration",
     ["Agents"],
     "Les cartes (agents, détenteurs de matériel, sans matériel, retours en retard) sont cohérentes avec la liste.", "m"),
])

# --------------------------------------------------------------------------------------
module("MAT", "Matières, étiquettes QR et scanner",
       "Vérifier l'enregistrement des biens durables, leur identification et leur historique.", [
    ("MAT-01", "Créer une matière minimale", "MAT", "Catégorie et emplacement existent",
     ["Matières > Ajouter", "Catégorie, nom, laisser l'état « Disponible », localisation, date d'achat (aujourd'hui ou avant)", "Enregistrer"],
     "La matière apparaît dans la liste. Sa fiche montre un code SYGEP-MAT-xxxxxx et, dans l'historique, une ligne « création ».", "C"),
    ("MAT-02", "État proposé à la création", "MAT", "—",
     ["Matières > Ajouter", "Ouvrir la liste « État »"],
     "« Disponible » est présélectionné ; « Affecté » et « En réparation » ne sont pas proposés.", "C"),
    ("MAT-03", "Date d'achat future", "MAT", "—",
     ["Saisir une date d'achat de demain", "Enregistrer"],
     "Refus avec message sous la date.", "M"),
    ("MAT-04", "Mise en service avant l'achat", "MAT", "—",
     ["Date d'achat 15/06, mise en service 01/06 (même année)", "Enregistrer"],
     "Refus avec message sous la date de mise en service.", "M"),
    ("MAT-05", "Numéro de série en double", "MAT", "Une matière avec le numéro de série S1 existe",
     ["Créer une autre matière avec le numéro S1"],
     "Refus (numéro déjà utilisé).", "C"),
    ("MAT-06", "Numéro de série vide accepté", "MAT", "—",
     ["Créer deux matières sans numéro de série"],
     "Les deux sont acceptées.", "M"),
    ("MAT-07", "Champs facultatifs", "MAT", "—",
     ["Créer une matière sans type, sans modèle, sans fournisseur, sans bon"],
     "Acceptée. Le tableau et la fiche n'affichent rien (ou un tiret) pour ces champs.", "M"),
    ("MAT-08", "Fournisseur et bon à choix unique", "MAT", "—",
     ["Matières > Ajouter", "Observer les listes Fournisseur et Bon"],
     "Chaque liste ne permet de choisir qu'un seul élément ; pas de boutons « tout sélectionner ».", "m"),
    ("MAT-09", "Photo de la matière", "MAT", "Une image de moins de 2 Mo",
     ["Glisser une image dans la zone Photos", "Enregistrer", "Ouvrir la fiche"],
     "La photo est enregistrée et visible (lien « voir » dans la fiche).", "M"),
    ("MAT-10", "Photo trop lourde", "MAT", "Une image de plus de 2 Mo",
     ["Glisser l'image dans la zone Photos"],
     "L'image est refusée avec un message de taille maximale.", "m"),
    ("MAT-11", "Modifier une matière", "MAT", "Une matière existe",
     ["Modifier : changer la localisation", "Enregistrer", "Ouvrir la fiche > Historique"],
     "Une ligne « modification » apparaît avec la nouvelle localisation et l'auteur.", "C"),
    ("MAT-12", "Fiche d'une matière", "MAT", "—",
     ["Matières > œil"],
     "Trois blocs : Situation actuelle, QR code, Historique. Le bouton Transférer n'est proposé que si la matière est détenue (affectée).", "M"),
    ("MAT-13", "Étiquette imprimable", "MAT", "—",
     ["Fiche > Étiquette"],
     "Une page imprimable affiche le QR code, le code et le nom de la matière.", "C"),
    ("MAT-14", "Télécharger le QR en SVG", "MAT", "—",
     ["Fiche > bouton SVG"],
     "Un fichier SVG du QR code est téléchargé.", "m"),
    ("MAT-15", "QR code : adresse correcte", "MAT", "APP_URL réglé",
     ["Scanner le QR code d'une étiquette avec un téléphone (ou lire l'adresse encodée)"],
     "L'adresse commence par APP_URL puis /q/SYGEP-MAT-xxxxxx.", "C"),
    ("MAT-16", "Liste : colonnes essentielles", "MAT", "—",
     ["Matières"],
     "Le tableau affiche : ID, catégorie, n° de série, nom, état, localisation, date d'achat, détenteur, actions.", "m"),
    ("MAT-17", "Liste : recherche, tri, pagination", "MAT", "Jeu de démonstration",
     ["Taper « HP » dans Rechercher", "Cliquer sur l'en-tête « Nom »", "Changer « Afficher » à 10"],
     "La liste se filtre, se trie et se pagine sans recharger la page.", "M"),
    ("MAT-18", "Liste : export", "MAT", "—",
     ["Exporter > Excel", "Exporter > PDF"],
     "Les fichiers contiennent les colonnes visibles et les lignes affichées.", "M"),
    ("MAT-19", "Liste : masquer une colonne", "MAT", "—",
     ["Colonnes > décocher « Localisation »"],
     "La colonne disparaît et n'est plus exportée.", "m"),
    ("MAT-20", "Supprimer une matière", "MAT", "Une matière de test sans affectation",
     ["Cliquer la corbeille", "Confirmer"],
     "Elle disparaît de la liste (suppression logique).", "M"),
    ("MAT-21", "Scanner : saisie du code", "MAT", "Code d'une matière connue (ex. SYGEP-MAT-000001)",
     ["Scanner un QR code > Saisie manuelle", "Saisir le code", "Valider"],
     "La fiche de la matière s'ouvre.", "C"),
    ("MAT-22", "Scanner : numéro de série ou lien", "MAT", "—",
     ["Saisir un numéro de série existant", "Puis le lien complet …/q/SYGEP-MAT-000001"],
     "Dans les deux cas la fiche correspondante s'ouvre.", "M"),
    ("MAT-23", "Scanner : code inconnu", "MAT", "—",
     ["Saisir un code inexistant"],
     "Message « Aucune matière ne correspond à … » ; on reste sur le scanner.", "M"),
    ("MAT-24", "Scanner : caméra en direct", "MAT", "Téléphone, site en HTTPS, étiquette imprimée",
     ["Appuyer sur Démarrer, autoriser la caméra", "Viser l'étiquette"],
     "Le téléphone vibre, « Code lu » s'affiche et la fiche s'ouvre.", "M"),
    ("MAT-25", "Scanner : photo d'un QR", "MAT", "Une image d'un QR code",
     ["Cliquer « Prendre une photo »", "Choisir l'image"],
     "Le code est lu et la fiche s'ouvre ; une image sans QR affiche un message d'échec.", "m"),
    ("MAT-26", "Page publique d'un QR", "—", "Déconnecté ; code d'une matière connue",
     ["Ouvrir /q/SYGEP-MAT-000001"],
     "Une page publique « Propriété du MEFPT » affiche seulement le nom, la catégorie et le code ; aucune information interne (détenteur, état…).", "C"),
    ("MAT-27", "Page publique : code inconnu", "—", "Déconnecté",
     ["Ouvrir /q/CODE-INEXISTANT"],
     "Une page « code inconnu » (erreur 404) s'affiche.", "m"),
    ("MAT-28", "QR scanné par un compte connecté", "MAT", "Connecté, droit de voir les matières",
     ["Ouvrir /q/SYGEP-MAT-000001"],
     "Redirection vers la fiche de gestion de la matière.", "M"),
    ("MAT-29", "Historique des matières", "MAT", "Quelques opérations réalisées",
     ["Historique matières"],
     "Chaque création, affectation, restitution, transfert ou changement d'état apparaît avec date, matière, détenteur, état, emplacement et auteur. Aucun bouton de modification.", "C"),
    ("MAT-30", "Photos et notes dans la fiche", "MAT", "Matière avec photo et notes",
     ["Ouvrir la fiche"],
     "Les photos, notes, modèle, fournisseur et bon sont affichés.", "m"),
])

module("AFF", "Affectations, restitutions et transferts",
       "Vérifier la remise de matériel, le bon imprimé, les retours et les statuts qui en découlent.", [
    ("AFF-01", "Dotation à un agent", "MAT", "Une matière Disponible ; un agent",
     ["Affectations > Nouvelle affectation", "Cocher la matière", "Choisir l'agent ; type « Dotation » ; date du jour", "Enregistrer"],
     "Un bon AFF-AAAA-nnnn est créé. La matière passe à « Affecté » et l'agent apparaît comme détenteur. L'historique contient une ligne « affectation ».", "C"),
    ("AFF-02", "Plusieurs matières, un seul bon", "MAT", "Trois matières Disponibles",
     ["Cocher les trois matières", "Choisir un agent", "Enregistrer"],
     "Un seul bon liste les trois matières ; la tuile « Matières affectées » augmente de 3.", "C"),
    ("AFF-03", "Affectation à un service", "MAT", "Une matière Disponible",
     ["Choisir « Aucun agent » et un service", "Enregistrer"],
     "Accepté : le bénéficiaire est le service.", "M"),
    ("AFF-04", "Aucun bénéficiaire", "MAT", "—",
     ["Cocher une matière", "Ne choisir ni agent ni service", "Enregistrer"],
     "Refus : « Choisissez un agent ou un service bénéficiaire. »", "C"),
    ("AFF-05", "Service repris de l'agent", "MAT", "—",
     ["Choisir un agent sans choisir de service"],
     "Le champ Service indique « Service de l'agent » (rempli automatiquement) ; le bon porte le service de l'agent.", "M"),
    ("AFF-06", "Seules les matières disponibles sont proposées", "MAT", "Des matières affectées et en panne existent",
     ["Ouvrir Nouvelle affectation"],
     "Les matières « Affecté » et « En panne » n'apparaissent pas. S'il n'y en a aucune de disponible, un message l'indique.", "C"),
    ("AFF-07", "Aucune matière cochée", "MAT", "—",
     ["Choisir un agent mais ne cocher aucune matière", "Enregistrer"],
     "Refus : « Sélectionnez au moins une matière. »", "C"),
    ("AFF-08", "Temporaire sans date de retour", "MAT", "—",
     ["Type « Mise à disposition temporaire »", "Laisser « Retour prévu » vide", "Enregistrer"],
     "Refus : date de retour prévue obligatoire pour ce type.", "C"),
    ("AFF-09", "Dotation sans date de retour", "MAT", "—",
     ["Type « Dotation »", "Laisser « Retour prévu » vide"],
     "Accepté.", "M"),
    ("AFF-10", "Retour avant l'affectation", "MAT", "—",
     ["Date d'affectation 20/10, retour prévu 10/10", "Enregistrer"],
     "Refus : la date de retour doit suivre la date d'affectation.", "M"),
    ("AFF-11", "Bon imprimé", "MAT", "Une affectation existe",
     ["Fiche de l'affectation > Imprimer le bon"],
     "Le bon affiche : en-tête République, numéro et date, bénéficiaire, conditions, tableau des matières (code, désignation, catégorie, série, modèle), texte d'engagement, signatures « Remis par » / « Reçu par ».", "C"),
    ("AFF-12", "Restitution partielle", "CPT", "Affectation de 3 matières",
     ["Fiche > Restituer", "Cocher une seule matière", "État « Bon état », date du jour", "Enregistrer"],
     "La matière redevient Disponible, sans détenteur. L'affectation passe à « Partielle ».", "C"),
    ("AFF-13", "Restitution complète", "CPT", "Affectation partielle (AFF-12)",
     ["Restituer les matières restantes"],
     "L'affectation passe à « Restituée ». Toutes les matières sont Disponibles.", "C"),
    ("AFF-14", "Restitution d'une matière endommagée", "CPT", "Une affectation ouverte",
     ["Restituer avec l'état « Endommagé »"],
     "La matière passe à « En panne », pas à « Disponible ».", "C"),
    ("AFF-15", "Restitution sans matière cochée", "CPT", "—",
     ["Restituer sans cocher de matière"],
     "Refus : « Cochez au moins une matière à restituer. »", "M"),
    ("AFF-16", "Restitution à date future", "CPT", "—",
     ["Saisir une date de retour de demain"],
     "Refus : « La date de retour ne peut pas être dans le futur. »", "M"),
    ("AFF-17", "Retard de restitution", "CPT", "Affectation temporaire avec retour prévu dépassé (jeu de démonstration)",
     ["Affectations > onglet « En retard »", "Tableau de bord"],
     "L'affectation figure dans « En retard » ; la tuile « Retours en retard » la compte.", "M"),
    ("AFF-18", "Transférer une matière", "CPT", "Une matière détenue par l'agent A",
     ["Fiche de la matière > Transférer", "Choisir l'agent B", "Enregistrer"],
     "L'ancienne affectation est clôturée pour cette matière (condition « Transféré »). Un nouveau bon est créé au nom de B. L'historique contient « transfert ».", "M"),
    ("AFF-19", "Transfert sans bénéficiaire", "CPT", "—",
     ["Transférer sans choisir ni agent ni service"],
     "Refus : « Choisissez le nouvel agent ou service bénéficiaire. »", "M"),
    ("AFF-20", "Supprimer un bon", "CPT", "Une affectation ouverte (de test)",
     ["Fiche > Supprimer ce bon", "Confirmer"],
     "Les matières encore détenues redeviennent Disponibles.", "M"),
    ("AFF-21", "Modifier une affectation", "CPT", "Une affectation existe",
     ["Modifier : changer le motif et la date de retour prévue", "Enregistrer"],
     "Les modifications sont enregistrées, avec les mêmes règles de dates.", "m"),
    ("AFF-22", "Filtres de la liste", "CPT", "Jeu de démonstration",
     ["Cliquer les onglets En cours / En retard / Restituées / Toutes"],
     "Les compteurs des onglets correspondent au contenu de la liste.", "m"),
    ("AFF-23", "Périmètre du comptable secondaire", "SEC", "Affectations de plusieurs services",
     ["Se connecter en SEC", "Ouvrir Affectations"],
     "Seules les affectations du service « CFP de Thiès » sont visibles.", "C"),
    ("AFF-24", "Redistribuer au sein de son service (transfert)", "SEC", "Une matière détenue par le service « CFP de Thiès » (sans agent précis)",
     ["Fiche de la matière > Transférer", "Choisir un agent du CFP de Thiès", "Enregistrer"],
     "Accepté : un bon est créé au nom de l'agent, la matière reste « Affecté » et rattachée au service. (Le comptable secondaire redistribue ainsi le matériel que le magasin central a remis à son service.)", "C"),
    ("AFF-25", "Impossible de transférer hors de son service", "SEC", "Une matière du CFP de Thiès ; un agent d'un AUTRE service",
     ["Tenter le transfert vers cet agent (ou saisir son identifiant)"],
     "Impossible : l'agent d'un autre service n'est pas accessible (erreur 404) ; aucun bon n'est créé et la matière ne change pas de service.", "C"),
])

module("INV", "Inventaires",
       "Vérifier les campagnes de contrôle physique, du démarrage au procès-verbal.", [
    ("INV-01", "Créer une campagne sur tout le parc", "CPT", "—",
     ["Inventaires > Ajouter", "Nom seulement ; laisser emplacement, service et catégorie sur « Tous »", "Enregistrer"],
     "La campagne INV-AAAA-nn est créée « En préparation ».", "C"),
    ("INV-02", "Campagne sans nom", "CPT", "—",
     ["Ajouter une campagne sans nom"],
     "Refus : « Donnez un nom à la campagne. »", "M"),
    ("INV-03", "Fin avant le début", "CPT", "—",
     ["Début prévu 20/10, fin prévue 10/10"],
     "Refus : « La date de fin doit suivre la date de début. »", "M"),
    ("INV-04", "Démarrer avec un périmètre", "CPT", "Campagne limitée au service « CFP de Thiès »",
     ["Cliquer « Démarrer la campagne »"],
     "La campagne passe « En cours ». Le tableau liste exactement les matières du service, toutes « À contrôler ».", "C"),
    ("INV-05", "Pointer à la main", "SEC", "Campagne en cours",
     ["Cliquer « Pointer » sur une matière"],
     "La matière passe « Contrôlée » ; l'avancement augmente.", "C"),
    ("INV-06", "Scanner une matière attendue", "SEC", "Campagne en cours",
     ["Scanner > saisir le code d'une matière attendue", "État « Bon état »"],
     "Message « Contrôlée : … » ; la matière est contrôlée.", "C"),
    ("INV-07", "Lire deux fois la même matière", "SEC", "Matière déjà contrôlée",
     ["Saisir de nouveau son code"],
     "Message « Déjà contrôlée » ; rien n'est doublé.", "M"),
    ("INV-08", "Matière hors périmètre", "SEC", "Une matière d'un autre emplacement ou service",
     ["Saisir son code dans le scanner"],
     "Message « Hors périmètre, ajoutée à la campagne » ; elle apparaît dans l'onglet Écarts.", "M"),
    ("INV-09", "Code inconnu", "SEC", "—",
     ["Saisir un code inexistant"],
     "Message « Code inconnu » ; aucune ligne créée.", "m"),
    ("INV-10", "Clôture réservée", "MAT", "Campagne en cours",
     ["Se connecter en MAT (administrateur des matières)", "Ouvrir la campagne"],
     "Le bouton « Clôturer la campagne » n'est pas proposé (droit réservé au comptable principal).", "C"),
    ("INV-11", "Clôturer : non vues = manquantes", "CPT", "Campagne en cours avec des matières non contrôlées",
     ["Clôturer la campagne"],
     "Les matières non contrôlées passent « Manquante ». La campagne est « Clôturée ».", "C"),
    ("INV-12", "Clôture avec mise à jour des fiches", "CPT", "Une matière contrôlée à un autre lieu que prévu ; une matière contrôlée « Hors service »",
     ["Clôturer avec « Mettre à jour les fiches » coché", "Ouvrir les deux matières"],
     "L'emplacement de la première est corrigé ; la seconde passe « En panne ». Chaque correction figure dans l'historique (« Mise à jour suite à l'inventaire … »).", "C"),
    ("INV-13", "Clôture sans mise à jour", "CPT", "Mêmes conditions",
     ["Clôturer en décochant « Mettre à jour les fiches »"],
     "Les fiches des matières ne changent pas.", "M"),
    ("INV-14", "Procès-verbal", "CPT", "Campagne clôturée",
     ["Procès-verbal"],
     "Le document affiche la campagne, les responsables (signatures), les matières manquantes, abîmées ou hors service, déplacées ou hors périmètre.", "C"),
    ("INV-15", "Campagne clôturée non modifiable", "CPT", "Campagne clôturée",
     ["Tenter de scanner une matière sur cette campagne"],
     "Message « La campagne n'est pas en cours ».", "M"),
    ("INV-16", "Supprimer une campagne", "CPT", "Une campagne de test",
     ["Supprimer la campagne", "Confirmer"],
     "Elle disparaît de la liste.", "m"),
    ("INV-17", "Scanner d'inventaire : lieu et état", "SEC", "Campagne en cours",
     ["Ouvrir Scanner", "Choisir « Hors service » et un lieu", "Saisir un code"],
     "La matière est contrôlée avec l'état « Hors service » et le lieu choisi.", "M"),
])

# --------------------------------------------------------------------------------------
module("STK", "Stock des consommables : articles et mouvements",
       "Vérifier que le solde est toujours juste, justifié et protégé.", [
    ("STK-01", "Créer un article avec stock initial", "MAT", "—",
     ["Stock consommables > Articles en stock > Ajouter", "Désignation « Article test », unité, seuil 5, quantité en stock aujourd'hui 20", "Enregistrer"],
     "L'article reçoit une référence ART-nnnn. Son solde est 20. Son historique contient un mouvement d'entrée « Stock initial ».", "C"),
    ("STK-02", "Seuil d'alerte obligatoire", "MAT", "—",
     ["Créer un article sans seuil d'alerte"],
     "Refus (champ obligatoire, astérisque rouge).", "M"),
    ("STK-03", "Champs obligatoires de l'article", "MAT", "—",
     ["Créer un article sans désignation ni unité"],
     "Refus avec message sous chaque champ.", "M"),
    ("STK-04", "Fiche d'un article", "MAT", "Article avec mouvements",
     ["Ouvrir la fiche de « Ramette papier A4 80 g »"],
     "La fiche montre le solde, les entrées et sorties du mois, la consommation moyenne mensuelle, la couverture en jours et la liste des mouvements.", "M"),
    ("STK-05", "Entrée valide", "MAT", "Article existant (solde S)",
     ["Mouvements de stock > Nouveau mouvement > Entrée", "Article, quantité 10, date du jour", "Enregistrer"],
     "Message « … nouveau solde S+10 ». Le solde de l'article est S+10. Le mouvement est numéroté MVT-AAAA-nnnnn.", "C"),
    ("STK-06", "Sortie valide", "MAT", "Article avec solde ≥ 5 ; un service",
     ["Nouveau mouvement > Sortie", "Article, quantité 5, service bénéficiaire", "Enregistrer"],
     "Le solde diminue de 5. Le mouvement indique le service bénéficiaire.", "C"),
    ("STK-07", "Sortie sans bénéficiaire", "MAT", "—",
     ["Sortie sans service ni agent"],
     "Refus : « Indiquez le service bénéficiaire de la sortie (ou l'agent demandeur). »", "C"),
    ("STK-08", "Sortie par un agent", "MAT", "Un agent d'un service",
     ["Sortie en choisissant l'agent demandeur et en laissant le service vide"],
     "Acceptée : le service de l'agent est repris comme bénéficiaire.", "M"),
    ("STK-09", "Sortie supérieure au stock", "MAT", "Article avec solde 11",
     ["Sortie de 50"],
     "Refus : « Stock insuffisant : il reste 11 … ». Le solde ne change pas.", "C"),
    ("STK-10", "Quantité nulle", "MAT", "—",
     ["Entrée ou sortie avec quantité 0"],
     "Refus : la quantité doit être supérieure à zéro.", "M"),
    ("STK-11", "Date future", "MAT", "—",
     ["Mouvement daté de demain"],
     "Refus : la date ne peut pas être dans le futur.", "M"),
    ("STK-12", "Ajustement après comptage", "CPT", "Article avec solde 20",
     ["Nouveau mouvement > Ajustement", "Quantité comptée 18, observations « casse »", "Enregistrer"],
     "Le solde devient 18. Le mouvement affiche un écart de −2.", "C"),
    ("STK-13", "Ajustement sans observations", "CPT", "—",
     ["Ajustement sans observations"],
     "Refus : « Expliquez l'écart constaté (comptage, casse, péremption…). »", "M"),
    ("STK-14", "Ajustement sans écart", "CPT", "Article avec solde 18",
     ["Ajustement avec quantité comptée 18"],
     "Refus : « La quantité comptée est identique au stock théorique : aucun ajustement nécessaire. »", "M"),
    ("STK-15", "Ajustement réservé", "MAT", "Compte administrateur des matières",
     ["Nouveau mouvement"],
     "Le choix « Ajustement » n'est pas proposé.", "C"),
    ("STK-16", "Article périssable : péremption obligatoire", "MAT", "Article coché « périssable » (ex. Détergent)",
     ["Entrée sans date de péremption"],
     "Refus : « Cet article est périssable : indiquez la date de péremption du lot reçu. »", "C"),
    ("STK-17", "Péremption antérieure", "MAT", "Article périssable",
     ["Entrée avec une péremption antérieure à la date du mouvement"],
     "Refus avec message sous la date de péremption.", "m"),
    ("STK-18", "Alerte de stock bas", "MAT", "Article avec solde 12 et seuil 10 ; un compte avec droit de modifier les articles (ex. ADM)",
     ["Sortie de 3 (le solde passe à 9)", "Ouvrir la cloche de ADM", "Tableau de bord"],
     "Une notification « Stock bas : … » est reçue. La tuile « Stock sous le seuil » compte l'article.", "C"),
    ("STK-19", "Alerte de rupture", "MAT", "Article déjà sous son seuil (solde 7, seuil 10)",
     ["Sortie de 7 (le solde passe à 0)"],
     "Notification « Rupture de stock : … », même si l'article était déjà sous le seuil.", "C"),
    ("STK-20", "Pas de notification répétée", "MAT", "Article déjà sous le seuil",
     ["Faire une nouvelle sortie (reste sous le seuil)"],
     "Aucune nouvelle notification n'est envoyée (l'alerte ne se déclenche qu'au franchissement).", "m"),
    ("STK-21", "Compte local : sorties seulement", "SEC", "Compte comptable secondaire",
     ["Nouveau mouvement"],
     "Seul « Sortie » est proposé ; une sortie pour son service est acceptée.", "C"),
    ("STK-22", "Journal : filtres", "CPT", "Jeu de démonstration",
     ["Mouvements de stock", "Choisir l'onglet Sortie, changer les dates, filtrer par article"],
     "Le journal ne montre que les mouvements correspondants.", "m"),
    ("STK-23", "Modification d'un article", "MAT", "Un article existe",
     ["Modifier l'article", "Constater que « Quantité en stock aujourd'hui » n'est pas proposée"],
     "La quantité n'est pas modifiable à la main (elle ne change que par des mouvements).", "M"),
])

module("BST", "Bons d'entrée et de sortie du stock",
       "Vérifier les bons multi-articles : exactitude, « tout ou rien », impression.", [
    ("BST-01", "Bon d'entrée à deux lignes", "MAT", "Deux articles existants ; un fournisseur",
     ["Bons de stock > Bon d'entrée", "Date du jour, fournisseur, N° de pièce", "Ajouter deux lignes : article A qté 20, article B qté 10", "Enregistrer"],
     "Un bon BE-AAAA-nnnn est créé avec 2 articles. Les soldes de A et B augmentent de 20 et 10. Deux mouvements sont rattachés au bon.", "C"),
    ("BST-02", "Bon de sortie à deux lignes", "MAT", "Mêmes articles avec stock suffisant",
     ["Bon de sortie", "Service bénéficiaire, agent demandeur", "Deux lignes : A qté 5, B qté 2", "Enregistrer"],
     "Un bon BS-AAAA-nnnn est créé. Les soldes de A et B diminuent de 5 et 2.", "C"),
    ("BST-03", "Même article deux fois", "MAT", "—",
     ["Ajouter deux lignes avec le même article"],
     "Refus : « Cet article figure déjà sur le bon : regroupez les quantités sur une seule ligne. »", "M"),
    ("BST-04", "Tout ou rien", "MAT", "Article A avec stock suffisant, article B avec stock faible",
     ["Bon de sortie avec A qté 1 et B qté supérieure à son stock", "Enregistrer", "Vérifier les soldes de A et B"],
     "Refus avec le message « Stock insuffisant » affiché sur la ligne de B. AUCUN bon n'est créé et le solde de A n'a pas changé.", "C"),
    ("BST-05", "Quantité nulle", "MAT", "—",
     ["Ligne avec quantité 0"],
     "Refus : la quantité doit être supérieure à zéro.", "M"),
    ("BST-06", "Bon sans article", "MAT", "—",
     ["Laisser la ligne sans article", "Enregistrer"],
     "Refus (l'article est obligatoire).", "M"),
    ("BST-07", "Sortie sans service", "MAT", "—",
     ["Bon de sortie sans service bénéficiaire"],
     "Refus : « Indiquez le service bénéficiaire du bon de sortie (ou l'agent demandeur). »", "C"),
    ("BST-08", "Entrée périssable sans péremption", "MAT", "Article périssable",
     ["Bon d'entrée avec cet article, sans date de péremption"],
     "Refus : « Article périssable : indiquez la date de péremption du lot. » Rien n'est créé.", "C"),
    ("BST-09", "Date future", "MAT", "—",
     ["Bon daté de demain"],
     "Refus : la date du bon ne peut pas être dans le futur.", "M"),
    ("BST-10", "Champs selon le type", "MAT", "—",
     ["Alterner Bon d'entrée / Bon de sortie dans le formulaire"],
     "En entrée : fournisseur, prix unitaire, péremption. En sortie : service et agent. Les autres champs sont masqués.", "m"),
    ("BST-11", "Choix d'un article", "MAT", "—",
     ["Choisir un article dans une ligne"],
     "L'unité et le stock actuel s'affichent sur la ligne.", "m"),
    ("BST-12", "Ajouter et retirer des lignes", "MAT", "—",
     ["Cliquer « Ajouter un article » trois fois", "Retirer une ligne avec la croix"],
     "Les lignes s'ajoutent et se retirent ; on ne peut pas retirer la dernière.", "m"),
    ("BST-13", "Bon d'entrée imprimé", "MAT", "Un bon d'entrée existe",
     ["Bons de stock > icône imprimante du bon d'entrée"],
     "Le document est titré « Bon d'entrée en magasin », avec fournisseur, tableau (code, désignation, quantité, unité, prix) et signatures « Livré par » / « Reçu par (magasinier) ».", "C"),
    ("BST-14", "Bon de sortie imprimé", "MAT", "Un bon de sortie existe",
     ["Imprimer le bon de sortie"],
     "Le document est titré « Bon de sortie de magasin », avec bénéficiaire, tableau et signatures « Remis par (magasinier) » / « Reçu par ».", "C"),
    ("BST-15", "Liste et filtres", "MAT", "Plusieurs bons",
     ["Bons de stock", "Cliquer les onglets Bon d'entrée / Bon de sortie"],
     "La liste est filtrée ; chaque ligne montre date, numéro, type, bénéficiaire, nombre d'articles, pièce, auteur.", "M"),
    ("BST-16", "Fiche d'un bon", "MAT", "—",
     ["Ouvrir la fiche (œil)"],
     "La fiche liste les articles, quantités, soldes après et références de mouvements.", "M"),
    ("BST-17", "Lien depuis le journal des mouvements", "MAT", "Un bon existe",
     ["Mouvements de stock", "Repérer la colonne « Bon »"],
     "Les mouvements créés par un bon affichent son numéro, cliquable.", "m"),
    ("BST-18", "Compte local", "SEC", "Compte comptable secondaire",
     ["Bons de stock", "Créer un bon", "Consulter la liste"],
     "Seul le bon de sortie est proposé. La liste ne contient que les bons de son service.", "C"),
    ("BST-19", "Numérotation", "MAT", "Deux bons créés dans la même année",
     ["Créer deux bons de sortie"],
     "Les numéros se suivent (BS-AAAA-0001, 0002…).", "m"),
])

module("INF", "Infrastructures", "Vérifier la hiérarchie, l'état et l'amortissement.", [
    ("INF-01", "Créer une structure", "INF", "—",
     ["Infrastructures > Ajouter", "Nom, nature « Structure », situation « En service »", "Enregistrer"],
     "La structure apparaît dans la liste.", "C"),
    ("INF-02", "Bâtiment rattaché à une structure", "INF", "Une structure existe",
     ["Nature « Bâtiment », rattaché à la structure"],
     "Accepté.", "C"),
    ("INF-03", "Bloc rattaché à un bâtiment", "INF", "Un bâtiment existe",
     ["Nature « Bloc », rattaché au bâtiment"],
     "Accepté.", "C"),
    ("INF-04", "Structure rattachée à autre chose", "INF", "—",
     ["Nature « Structure », rattachée à un bâtiment"],
     "Refus : « Une structure est un site principal : elle ne se rattache à rien. »", "M"),
    ("INF-05", "Bâtiment rattaché à un bloc", "INF", "Un bloc existe",
     ["Nature « Bâtiment », rattaché à un bloc"],
     "Refus : « Un bâtiment se rattache à une structure. »", "M"),
    ("INF-06", "Amortissement incomplet", "INF", "—",
     ["Renseigner seulement la valeur d'origine", "Enregistrer"],
     "Refus : demande de la date de mise en service et de la durée, avec un message sous chaque champ manquant.", "C"),
    ("INF-07", "Amortissement complet", "INF", "—",
     ["Valeur 400 000 000, mise en service il y a 10 ans, durée 40 ans", "Enregistrer", "Ouvrir la fiche"],
     "La fiche affiche l'annuité (10 000 000), la part amortie (≈ 25 %), la valeur nette (≈ 300 000 000) et le plan année par année.", "C"),
    ("INF-08", "Sans valorisation", "INF", "—",
     ["Laisser les trois champs d'amortissement vides"],
     "Accepté ; aucun plan d'amortissement n'est affiché.", "m"),
    ("INF-09", "Visite future", "INF", "—",
     ["Date de dernière visite de demain"],
     "Refus.", "m"),
    ("INF-10", "Valeurs négatives", "INF", "—",
     ["Surface −5"],
     "Refus.", "m"),
    ("INF-11", "Durée hors limites", "INF", "—",
     ["Durée 0, puis 150"],
     "Refus (la durée va de 1 à 100 ans).", "m"),
    ("INF-12", "Fiche d'une infrastructure", "INF", "Infrastructure avec projet et demande",
     ["Ouvrir la fiche"],
     "La fiche montre les bâtiments/blocs rattachés, les projets liés, la maintenance, et le bouton « Signaler un problème ».", "M"),
    ("INF-13", "Signaler un problème", "INF", "—",
     ["Fiche > Signaler un problème"],
     "Le formulaire de demande de maintenance s'ouvre avec l'infrastructure déjà choisie.", "m"),
    ("INF-14", "Chiffres clés et état", "INF", "Jeu de démonstration",
     ["Infrastructures"],
     "Les chiffres clés (nombre, situation, état) sont cohérents avec la liste.", "m"),
])

module("PRJ", "Projets, jalons, chefs de projet, intervenants et rapports",
       "Vérifier le suivi des chantiers et le calcul automatique de l'avancement.", [
    ("PRJ-01", "Créer un projet planifié", "INF", "—",
     ["Projets > Ajouter", "Intitulé, nature, statut « Planifié »", "Enregistrer"],
     "Le projet reçoit une référence PRJ-AAAA-nn. Message d'invitation à ajouter des jalons.", "C"),
    ("PRJ-02", "Projet lancé sans date de démarrage", "INF", "—",
     ["Statut « En cours », date de démarrage vide", "Enregistrer"],
     "Refus : « Indiquez la date de démarrage : le projet est déjà lancé. »", "C"),
    ("PRJ-03", "Fin avant démarrage", "INF", "—",
     ["Démarrage 20/10, fin prévue 10/10"],
     "Refus : « La date de fin doit suivre la date de début. »", "M"),
    ("PRJ-04", "Engagé supérieur au budget", "INF", "—",
     ["Budget 1 000 000, montant engagé 1 500 000"],
     "Une alerte rouge s'affiche en direct sous le champ ; à l'enregistrement : « Le montant engagé dépasse le budget prévu… ».", "M"),
    ("PRJ-05", "Ajouter des jalons", "INF", "Un projet existe",
     ["Fiche du projet > Jalons : ajouter A (poids 1), B (poids 3)"],
     "Les jalons apparaissent dans l'ordre. L'avancement reste 0 %.", "C"),
    ("PRJ-06", "Avancement pondéré", "INF", "Jalons A (1) et B (3)",
     ["Cocher le jalon B"],
     "L'avancement passe à 75 % (3/4). Le projet « Planifié » devient « En cours ».", "C"),
    ("PRJ-07", "Projet terminé automatiquement", "INF", "—",
     ["Cocher aussi le jalon A"],
     "L'avancement est 100 % ; le projet passe « Terminé ».", "C"),
    ("PRJ-08", "Décocher un jalon", "INF", "Projet terminé",
     ["Décocher le jalon A"],
     "L'avancement redescend (75 %) et le projet repasse « En cours ».", "M"),
    ("PRJ-09", "Projet terminé sans jalon", "INF", "—",
     ["Créer un projet « Terminé » avec date de démarrage, sans jalon, avancement laissé à 0"],
     "L'avancement enregistré est 100 %.", "M"),
    ("PRJ-10", "Avancement verrouillé", "INF", "Projet avec jalons",
     ["Modifier le projet"],
     "Le champ Avancement est désactivé avec la mention « calculé à partir des jalons ».", "m"),
    ("PRJ-11", "Projet en retard", "INF", "Projet « En cours » dont la fin prévue est dépassée",
     ["Projets", "Chiffres clés"],
     "Il est compté en retard.", "m"),
    ("PRJ-12", "Ajouter un intervenant au projet", "INF", "Un intervenant existe",
     ["Fiche du projet > Intervenants > Ajouter au projet"],
     "L'intervenant apparaît dans la liste du projet.", "M"),
    ("PRJ-13", "Créer un chef de projet", "INF", "—",
     ["Chefs de projet > Ajouter", "Nom, prénom, téléphone", "Enregistrer"],
     "Accepté ; il est proposé dans le formulaire des projets.", "M"),
    ("PRJ-14", "Chef de projet sans contact", "INF", "—",
     ["Nom et prénom seulement"],
     "Refus : « Indiquez au moins un téléphone ou un e-mail… »", "M"),
    ("PRJ-15", "Chef de projet sans nom", "INF", "—",
     ["Laisser nom et prénom vides"],
     "Refus.", "C"),
    ("PRJ-16", "Entreprise sans organisme", "INF", "—",
     ["Intervenants > Ajouter", "Type « Entreprise de travaux », organisme vide, un téléphone"],
     "Refus : « Indiquez l'entreprise ou l'organisme de cet intervenant. »", "M"),
    ("PRJ-17", "Technicien indépendant", "INF", "—",
     ["Type « Technicien / artisan », nom, téléphone, organisme vide"],
     "Accepté.", "m"),
    ("PRJ-18", "Intervenant sans moyen de contact", "INF", "—",
     ["Ni téléphone ni e-mail"],
     "Refus : au moins un des deux.", "M"),
    ("PRJ-19", "Rapport de projet", "INF", "Un projet et un fichier de moins de 25 Mo",
     ["Rapports > Ajouter", "Titre, fichier, date du jour, projet", "Enregistrer"],
     "Le rapport apparaît dans la liste et dans la fiche du projet.", "M"),
    ("PRJ-20", "Rapport : date future ou sans projet", "INF", "—",
     ["Date de demain, puis aucun projet"],
     "Refus dans les deux cas.", "m"),
])

# --------------------------------------------------------------------------------------
module("MNT", "Demandes de maintenance (circuit complet)",
       "Vérifier chaque étape du circuit et ses effets sur les matières et infrastructures.", [
    ("MNT-01", "Déposer une demande valide", "AGT", "Une matière du service existe",
     ["Demandes de maintenance > Ajouter", "Objet, type Corrective, priorité Normale, Concerne « Matière », choisir la matière", "Décrire le problème", "Enregistrer"],
     "La demande reçoit une référence DMT-AAAA-nnn au statut « Soumise ». Message « transmise pour validation ».", "C"),
    ("MNT-02", "Description obligatoire", "AGT", "—",
     ["Déposer une demande sans description"],
     "Refus : « Décrivez le problème (constat, localisation, depuis quand)… »", "C"),
    ("MNT-03", "Cible infrastructure sans infrastructure", "AGT", "—",
     ["Concerne « Bâtiment / infrastructure », aucune infrastructure choisie"],
     "Refus : « Choisissez l'infrastructure concernée. »", "M"),
    ("MNT-04", "Cible matière sans matière", "AGT", "—",
     ["Concerne « Matière / équipement », aucune matière choisie"],
     "Refus : « Choisissez la matière concernée. »", "M"),
    ("MNT-05", "Notification au responsable", "MNT", "Demande MNT-01 déposée",
     ["Se connecter en MNT", "Ouvrir la cloche"],
     "Une notification « Nouvelle demande de maintenance … à valider » est présente, avec un lien vers la demande.", "M"),
    ("MNT-06", "Avis technique favorable", "MNT", "Demande « Soumise »",
     ["Ouvrir la demande", "Bloc « Avis technique » > Valider"],
     "Statut « Attente du Directeur ». Le Directeur reçoit une notification.", "C"),
    ("MNT-07", "Rejet sans motif", "MNT", "Demande « Soumise »",
     ["Rejeter sans saisir de motif"],
     "Refus : « Indiquez le motif du rejet. »", "C"),
    ("MNT-08", "Rejet avec motif", "MNT", "Demande « Soumise »",
     ["Rejeter avec un motif"],
     "Statut « Rejetée ». Le demandeur est notifié ; le motif est visible dans le suivi.", "C"),
    ("MNT-09", "Approbation du Directeur", "DIR", "Demande « Attente du Directeur »",
     ["Ouvrir la demande", "Bloc « Approbation du Directeur » > Valider"],
     "Statut « Approuvée ». Le responsable maintenance est notifié.", "C"),
    ("MNT-10", "Le Directeur ne donne pas l'avis technique", "DIR", "Demande « Soumise »",
     ["Ouvrir la demande"],
     "Aucun bouton de décision n'est proposé (ou erreur 403 si l'action est forcée).", "M"),
    ("MNT-11", "Le responsable maintenance n'approuve pas", "MNT", "Demande « Attente du Directeur »",
     ["Ouvrir la demande"],
     "Aucun bouton d'approbation n'est proposé.", "M"),
    ("MNT-12", "Planifier", "MNT", "Demande « Approuvée »",
     ["Bloc « Planifier » : date prévue, échéance, technicien, instructions", "Enregistrer"],
     "Statut « Planifiée ». Une tâche « [DMT-…] Objet » apparaît dans Tâches et dans le calendrier. Le technicien est notifié.", "C"),
    ("MNT-13", "Planification : date prévue obligatoire", "MNT", "—",
     ["Planifier sans date prévue"],
     "Refus.", "M"),
    ("MNT-14", "Planification : échéance avant la date prévue", "MNT", "—",
     ["Échéance antérieure à la date prévue"],
     "Refus (l'échéance doit être égale ou postérieure).", "M"),
    ("MNT-15", "Démarrer l'intervention sur une matière", "MNT", "Demande planifiée portant sur une matière",
     ["Démarrer l'intervention"],
     "Statut « En cours ». La matière passe « En réparation ». La tâche passe « En cours ».", "C"),
    ("MNT-16", "Démarrer sur une infrastructure urgente", "MNT", "Demande urgente sur une infrastructure « En service »",
     ["Démarrer l'intervention"],
     "L'infrastructure passe « En maintenance ».", "M"),
    ("MNT-17", "Clôture sans compte rendu", "MNT", "Demande « En cours »",
     ["Clôturer sans saisir l'intervention réalisée"],
     "Refus : « Décrivez l'intervention réalisée. »", "C"),
    ("MNT-18", "Clôture avec remise en service", "MNT", "Demande en cours sur une matière",
     ["Clôturer : compte rendu, coût, cocher « Remise en service »"],
     "Statut « Terminée ». La matière redevient « Disponible » (ou « Affecté » si elle était affectée). Le demandeur est notifié. La tâche passe « Terminée ».", "C"),
    ("MNT-19", "Clôture sans remise en service", "MNT", "Demande en cours sur une matière",
     ["Clôturer sans cocher « Remise en service »"],
     "La matière passe « En panne ».", "C"),
    ("MNT-20", "Clôture sur une infrastructure", "MNT", "Infrastructure « En maintenance »",
     ["Clôturer en indiquant l'état constaté « Bon »"],
     "L'infrastructure repasse « En service », son état devient « Bon » et sa date de dernière visite est celle du jour.", "M"),
    ("MNT-21", "Visibilité pour un agent", "AGT", "Demandes de plusieurs services",
     ["Se connecter en AGT", "Ouvrir Demandes de maintenance"],
     "Il ne voit que ses demandes et celles du matériel de son service.", "C"),
    ("MNT-22", "Liste et chiffres clés", "MNT", "Jeu de démonstration",
     ["Demandes de maintenance"],
     "Les chiffres (en attente, en cours, terminées…) sont cohérents avec la liste ; les statuts ont des pastilles de couleur.", "m"),
    ("MNT-23", "Supprimer une demande", "ADM", "Une demande de test",
     ["Supprimer la demande", "Confirmer"],
     "Elle disparaît de la liste.", "m"),
])

module("PRV", "Maintenance préventive",
       "Vérifier la génération automatique des demandes d'entretien.", [
    ("PRV-01", "Créer un plan valide", "MNT", "Une matière ou infrastructure",
     ["Maintenance préventive > Ajouter", "Opération, cible, périodicité Semestrielle, échéance dans 20 jours, délai 7 jours, points de contrôle", "Enregistrer"],
     "Le plan apparaît, actif, avec sa prochaine échéance.", "C"),
    ("PRV-02", "Points de contrôle obligatoires", "MNT", "—",
     ["Créer un plan sans points de contrôle"],
     "Refus : « Listez les points de contrôle à vérifier à chaque opération. »", "M"),
    ("PRV-03", "Échéance dans le passé", "MNT", "—",
     ["Prochaine échéance = hier (à la création)"],
     "Refus : « La prochaine échéance ne peut pas être dans le passé. »", "M"),
    ("PRV-04", "Délai supérieur à la périodicité", "MNT", "—",
     ["Périodicité Mensuelle, délai 45 jours"],
     "Refus : « Le délai de création doit rester inférieur à la périodicité du plan. »", "M"),
    ("PRV-05", "Lancer un plan", "MNT", "Un plan actif",
     ["Cliquer ⚡ « Lancer » sur le plan"],
     "Une demande préventive est créée au statut « Attente du Directeur » (avis technique déjà inscrit). Le Directeur et le responsable du plan sont notifiés.", "C"),
    ("PRV-06", "Pas de doublon", "MNT", "Demande préventive déjà générée et encore ouverte",
     ["Cliquer de nouveau « Lancer »"],
     "Aucune seconde demande n'est créée.", "C"),
    ("PRV-07", "L'échéance avance", "MNT", "Plan lancé (PRV-05)",
     ["Consulter la prochaine échéance du plan"],
     "Elle a avancé d'une période (+ 6 mois pour un plan semestriel).", "M"),
    ("PRV-08", "Commande automatique", "—", "Accès au serveur ; un plan dont la date « échéance − délai » est atteinte",
     ["Exécuter php artisan sygep:maintenance-preventive"],
     "« n demande(s) préventive(s) créée(s) » ; sinon « Aucun entretien à programmer ».", "C"),
    ("PRV-09", "Plan inactif", "MNT", "Un plan dont l'échéance est atteinte",
     ["Décocher « Plan actif »", "Exécuter la commande ou cliquer Lancer"],
     "Aucune demande n'est générée.", "M"),
    ("PRV-10", "Planificateur installé", "—", "Accès au serveur",
     ["Vérifier la présence de la ligne cron « schedule:run » ; observer le lendemain 6 h 30"],
     "Les plans échus génèrent leur demande sans intervention.", "C"),
    ("PRV-11", "Clôture d'une demande préventive", "MNT", "Demande préventive approuvée puis exécutée",
     ["Clôturer l'intervention"],
     "La « dernière réalisation » du plan est mise à la date du jour.", "m"),
])

module("TCH", "Tâches, étiquettes et calendrier", "Vérifier l'organisation du travail des équipes.", [
    ("TCH-01", "Créer une tâche valide", "MNT", "—",
     ["Tâches > Ajouter", "Nom, état « Ouverte », date prévue", "Enregistrer"],
     "La tâche apparaît dans la liste et dans le calendrier.", "C"),
    ("TCH-02", "Date limite avant la date prévue", "MNT", "—",
     ["Date prévue 20/10, date limite 10/10"],
     "Refus avec message sous la date limite.", "M"),
    ("TCH-03", "Statuts en français", "MNT", "—",
     ["Statuts des tâches"],
     "Ouverte, En cours, Terminée sont présents.", "C"),
    ("TCH-04", "Équipement affiché par nom et code", "MNT", "—",
     ["Tâches > Ajouter", "Ouvrir la liste « Équipement »"],
     "Chaque ligne affiche le nom suivi du code (et non un numéro de série éventuellement vide).", "M"),
    ("TCH-05", "Étiquettes", "MNT", "—",
     ["Étiquettes > Ajouter « Urgent »", "L'associer à une tâche"],
     "L'étiquette apparaît sur la tâche.", "m"),
    ("TCH-06", "Calendrier", "MNT", "Une tâche avec date limite et une sans date limite",
     ["Calendrier"],
     "Les tâches qui ont une date limite apparaissent à cette date ; celle qui n'en a pas n'apparaît pas.", "M"),
    ("TCH-07", "Tâche issue d'une maintenance", "MNT", "Demande planifiée (MNT-12)",
     ["Tâches"],
     "La tâche créée automatiquement existe, avec l'état qui suit l'intervention.", "M"),
    ("TCH-08", "Assigner une tâche", "MNT", "—",
     ["Choisir un utilisateur dans « Affecté à »"],
     "La tâche affiche le responsable.", "m"),
])

module("RPT", "Rapports périodiques", "Vérifier les bilans destinés à la direction.", [
    ("RPT-01", "Rapport mensuel", "DIR", "Nous sommes le 15 octobre (exemple)",
     ["Rapports périodiques > carte « Rapport mensuel »"],
     "Un nouvel onglet s'ouvre sur « Septembre 2026 » (le mois précédent), toutes rubriques.", "C"),
    ("RPT-02", "Rapport trimestriel", "DIR", "Même date",
     ["Carte « Rapport trimestriel »"],
     "Période : du 01/07 au 30/09 (le trimestre précédent).", "M"),
    ("RPT-03", "Bilan semestriel", "DIR", "Même date",
     ["Carte « Bilan semestriel »"],
     "Période : du 01/01 au 30/06 (le semestre précédent, terminé).", "C"),
    ("RPT-04", "Bilan annuel", "DIR", "Même date",
     ["Carte « Bilan annuel »"],
     "Période : du 01/01 au 31/12 de l'année précédente.", "M"),
    ("RPT-05", "Composer un rapport", "DIR", "—",
     ["Choisir « Période personnalisée », renseigner du…au…", "Décocher une rubrique", "Générer"],
     "Le rapport couvre la période choisie et n'inclut que les rubriques cochées.", "M"),
    ("RPT-06", "Impression / PDF", "DIR", "Un rapport ouvert",
     ["Utiliser « Imprimer » puis « Enregistrer au format PDF »"],
     "La mise en page est correcte (A4), sans la barre d'outils.", "M"),
    ("RPT-07", "Droit d'accès", "AGT", "Compte agent",
     ["Saisir l'adresse /admin/rapports-periodiques"],
     "Erreur 403.", "M"),
])

module("NTF", "Notifications", "Vérifier l'envoi et la lecture des notifications internes.", [
    ("NTF-01", "Envoyer à tous", "ADM", "—",
     ["Envoi de notifications > Ajouter", "Message, destinataires « Tous les utilisateurs »", "Enregistrer"],
     "Message « Notification envoyée à N utilisateur(s) ». Chaque compte voit la notification dans sa cloche.", "C"),
    ("NTF-02", "Envoyer à un rôle", "ADM", "—",
     ["Destinataires « Par rôle », choisir « Agent / demandeur »"],
     "Seuls les comptes de ce rôle reçoivent la notification.", "M"),
    ("NTF-03", "Envoyer à des personnes", "ADM", "—",
     ["Destinataires « Personnes choisies », en cocher deux"],
     "Seules ces deux personnes la reçoivent.", "M"),
    ("NTF-04", "Rôle sans sélection", "ADM", "—",
     ["« Par rôle » sans choisir de rôle"],
     "Refus : « Choisissez au moins un rôle. »", "M"),
    ("NTF-05", "Message trop long", "ADM", "—",
     ["Message de plus de 255 caractères"],
     "Refus.", "m"),
    ("NTF-06", "Adresse personnalisée", "ADM", "—",
     ["Page « personnalisée » sans adresse, puis avec « abc »"],
     "Refus dans les deux cas ; une adresse https://… complète est acceptée.", "m"),
    ("NTF-07", "Ouvrir une notification", "AGT", "Notification avec lien",
     ["Cliquer la cloche puis la notification"],
     "La page cible s'ouvre ; la notification est marquée lue ; le compteur diminue.", "C"),
    ("NTF-08", "Tout marquer comme lu", "AGT", "Plusieurs notifications non lues",
     ["Cliquer « Tout marquer comme lu »"],
     "Le compteur de la cloche tombe à zéro.", "M"),
    ("NTF-09", "Notifications automatiques", "ADM", "Événements réalisés (stock bas, demande déposée…)",
     ["Ouvrir la cloche des comptes concernés"],
     "Les notifications automatiques décrites au guide (5.7) sont présentes.", "M"),
])

module("DSH", "Tableau de bord, listes et ergonomie",
       "Vérifier l'affichage général, la cohérence des chiffres et l'utilisabilité.", [
    ("DSH-01", "Tuiles de chiffres clés", "ADM", "Jeu de démonstration",
     ["Ouvrir le tableau de bord"],
     "Huit tuiles s'alignent en deux rangées de quatre, de même hauteur.", "M"),
    ("DSH-02", "Cohérence des chiffres", "ADM", "—",
     ["Comparer chaque tuile au module correspondant (ex. Disponibles ↔ liste filtrée)"],
     "Les chiffres du tableau de bord correspondent aux listes.", "C"),
    ("DSH-03", "Graphiques en bas du tableau de bord", "ADM", "—",
     ["Faire défiler le tableau de bord"],
     "Les listes (mouvements, projets, maintenance) précèdent les graphiques placés en bas de page.", "m"),
    ("DSH-04", "Bloc Graphiques repliable", "ADM", "—",
     ["Ouvrir Matières", "Cliquer « Graphiques (n) »", "Aller sur un autre module"],
     "Fermé par défaut ; une fois ouvert, il reste ouvert sur les autres modules (choix mémorisé).", "m"),
    ("DSH-05", "Actions rapides", "ADM", "—",
     ["Cliquer chaque bouton d'action rapide du tableau de bord"],
     "Chaque bouton ouvre le bon formulaire. Un bouton n'apparaît que si le droit existe.", "M"),
    ("DSH-06", "Recherche globale", "ADM", "—",
     ["Taper « HP » dans la barre du haut"],
     "Des résultats cliquables (matières, fournisseurs, bons…) apparaissent.", "M"),
    ("DSH-07", "Actions alignées dans les tableaux", "ADM", "—",
     ["Ouvrir Utilisateurs, Matières, Affectations, Plans de maintenance"],
     "Les icônes d'action sont alignées sur une seule ligne dans tous les tableaux.", "m"),
    ("DSH-08", "Menu : déconnexion en bas", "ADM", "Plusieurs groupes de menu ouverts, fenêtre basse",
     ["Ouvrir tous les groupes du menu"],
     "Le bouton Déconnexion reste visible en bas, sans défiler.", "m"),
    ("DSH-09", "Sous-menu actif lisible", "ADM", "—",
     ["Ouvrir « Bons de stock »"],
     "L'entrée du menu est surlignée en bleu avec un texte blanc lisible.", "m"),
    ("DSH-10", "Menus déroulants", "ADM", "—",
     ["Cliquer chaque groupe du menu", "Cliquer le menu du compte et la cloche"],
     "Tout s'ouvre et se ferme ; les liens fonctionnent.", "C"),
    ("DSH-11", "Affichage sur téléphone", "ADM", "Téléphone ou fenêtre étroite (≈ 390 px)",
     ["Ouvrir le tableau de bord, une liste, un formulaire"],
     "Pas de défilement horizontal de la page ; les tuiles passent sur deux colonnes ; le menu s'ouvre par le bouton en haut.", "M"),
    ("DSH-12", "Libellés français des tableaux", "ADM", "Accès Internet",
     ["Ouvrir une liste"],
     "« Afficher … entrées », « Rechercher », pagination en français.", "m"),
    ("DSH-13", "Message de confirmation", "MAT", "—",
     ["Enregistrer un bon de stock (ou une affectation, un mouvement de stock, une clôture d'inventaire)"],
     "Un bandeau vert confirme l'opération (ex. « Bon de sortie BS-… enregistré »). Les simples créations de référentiels (catégorie, service…) reviennent à la liste sans bandeau.", "m"),
])

module("PUB", "Site public et page Contact", "Vérifier ce que voient les visiteurs non connectés.", [
    ("PUB-01", "Page d'accueil", "—", "Déconnecté",
     ["Ouvrir /"],
     "La page de présentation de SYGEP s'affiche, avec un accès à la connexion.", "M"),
    ("PUB-02", "Accueil pour un connecté", "ADM", "Connecté",
     ["Ouvrir /"],
     "Redirection vers le tableau de bord.", "m"),
    ("PUB-03", "Envoyer un message", "—", "Déconnecté",
     ["Ouvrir /contact", "Remplir nom, e-mail, objet, message", "Envoyer"],
     "Message de remerciement. Les comptes ayant le droit de lire les messages reçoivent une notification et voient le bandeau « nouveau message de contact à lire ».", "C"),
    ("PUB-04", "Champs obligatoires", "—", "—",
     ["Envoyer le formulaire vide"],
     "Refus avec messages.", "M"),
    ("PUB-05", "Limitation d'envoi", "—", "—",
     ["Envoyer six messages en une minute"],
     "Le sixième est refusé (limite de 5 par minute).", "m"),
    ("PUB-06", "Coordonnées", "—", ".env renseigné",
     ["Ouvrir /contact"],
     "Adresse, téléphone, e-mail et horaires correspondent aux valeurs de CONTACT_* dans .env.", "m"),
    ("PUB-07", "Lire un message reçu", "ADM", "Un message reçu",
     ["Ouvrir la notification ou la liste des messages de contact"],
     "Le message est lisible ; il est marqué lu.", "M"),
])

module("SEC", "Droits et isolation des données",
       "Vérifier que personne ne voit ni ne fait plus que ce qui lui est permis.", [
    ("SEC-01", "Isolation du comptable secondaire", "SEC", "Données de plusieurs services (jeu de démonstration)",
     ["Se connecter en SEC", "Ouvrir Matières, Agents, Affectations, Mouvements de stock, Inventaires"],
     "Il ne voit que les données du service « CFP de Thiès ».", "C"),
    ("SEC-02", "Création hors de son service", "SEC", "—",
     ["Tenter de créer une affectation ou une sortie de stock pour un autre service"],
     "Impossible : choix absent, refusé, ou erreur « Cette opération concerne un autre service que le vôtre ».", "C"),
    ("SEC-03", "Agent : matériel de son service", "AGT", "—",
     ["Ouvrir Matières"],
     "Seules les matières de son service sont visibles, en lecture seule.", "C"),
    ("SEC-04", "Droits non cumulés par erreur", "AGT", "—",
     ["Chercher dans le menu Stock, Infrastructures, Rapports, Rôles"],
     "Aucun de ces modules n'est visible.", "C"),
    ("SEC-05", "403 sur adresse directe", "AGT", "—",
     ["Saisir /admin/stock-items, /admin/projects, /admin/roles"],
     "Erreur 403 à chaque fois.", "C"),
    ("SEC-06", "Directeur : aucune modification", "DIR", "—",
     ["Tenter d'ouvrir /admin/assets/create"],
     "Erreur 403.", "C"),
    ("SEC-07", "Ajustement de stock réservé", "MAT", "—",
     ["Tenter l'ajustement en forçant le type dans l'adresse (…/stock-movements/create?type=ajustement)"],
     "Le formulaire ne propose pas l'ajustement ; l'envoi est refusé.", "C"),
    ("SEC-08", "Clôture d'inventaire réservée", "MAT", "—",
     ["Tenter de clôturer une campagne"],
     "Bouton absent ; action interdite (403).", "C"),
    ("SEC-09", "Mot de passe non lisible", "—", "Accès à la base",
     ["Consulter la colonne password de la table users"],
     "Les mots de passe sont chiffrés (empreinte commençant par $2y$), jamais en clair.", "C"),
    ("SEC-10", "Compte supprimé ou désapprouvé", "ADM", "Un utilisateur connecté dans un autre navigateur",
     ["Décocher « Approuvé » sur ce compte", "Actualiser une page dans l'autre navigateur"],
     "L'utilisateur est déconnecté et ne peut plus se connecter.", "M"),
    ("SEC-12", "Adresse directe d'une matière d'un autre service", "SEC", "Connaître l'identifiant d'une matière d'un autre service (ex. /admin/assets/1)",
     ["Saisir directement l'adresse /admin/assets/1 (matière d'un autre service)"],
     "Erreur 404 : la matière n'est pas accessible. Même contrôle pour les affectations, mouvements et bons de stock d'un autre service.", "C"),
    ("SEC-11", "Mode débogage éteint", "—", "Serveur de production",
     ["Provoquer une erreur (adresse inexistante, puis erreur serveur simulée)"],
     "Aucune trace technique (chemins, requêtes SQL) n'est affichée à l'utilisateur.", "C"),
])

module("INS", "Installation et exploitation", "Vérifier le déploiement, la sauvegarde et la reprise.", [
    ("INS-01", "Installation sur base vide", "—", "Base vide, .env configuré",
     ["php artisan migrate --seed"],
     "Aucune erreur. La base contient 149 droits, 9 rôles métier + le rôle User, les statuts de matières et de tâches, et le compte admin.", "C"),
    ("INS-02", "Seeders relançables", "—", "Installation faite",
     ["php artisan db:seed"],
     "Aucune erreur ni doublon.", "M"),
    ("INS-03", "Rôles du compte admin", "ADM", "Installation neuve",
     ["Utilisateurs > admin@admin.com"],
     "Le compte n'a que le rôle « Super administrateur ».", "C"),
    ("INS-04", "Rôle de l'inscription libre", "—", "Installation neuve",
     ["Créer un compte via /register", "Observer ses rôles"],
     "Rôle « User » uniquement, droits très limités, compte non approuvé.", "C"),
    ("INS-05", "Jeu de démonstration", "—", "Base de TEST",
     ["php artisan db:seed --class=DemoDataSeeder", "Le relancer"],
     "Les données sont créées ; la seconde exécution indique que les données existent déjà et ne fait rien.", "M"),
    ("INS-06", "Fichiers déposés", "ADM", "storage:link exécuté",
     ["Ajouter une photo à une matière", "Ouvrir la fiche"],
     "La photo s'affiche (le lien public vers storage fonctionne).", "M"),
    ("INS-07", "Sauvegarde et restauration", "—", "Accès au serveur",
     ["Faire un mysqldump", "Restaurer dans une base vide", "Pointer un .env de test dessus", "Se connecter"],
     "L'application fonctionne avec les données restaurées.", "C"),
    ("INS-08", "Mise à jour", "—", "Sauvegarde faite",
     ["git pull", "composer install --no-dev", "php artisan migrate --force", "php artisan view:clear"],
     "Aucune erreur ; l'application fonctionne ; les données sont intactes.", "C"),
    ("INS-09", "HTTPS", "—", "Serveur de production",
     ["Ouvrir le site en https:// et tenter d'ouvrir http://"],
     "Le site est servi en HTTPS ; la caméra du scanner fonctionne sur téléphone.", "C"),
    ("INS-10", "Permissions des dossiers", "—", "Serveur",
     ["Vérifier que storage/ et bootstrap/cache/ sont modifiables par le serveur web"],
     "Les journaux s'écrivent ; aucune erreur de permission.", "M"),
    ("INS-11", "Configuration de production", "—", "Serveur",
     ["Lire le fichier .env"],
     "APP_ENV=production, APP_DEBUG=false, APP_URL définitif, accès base corrects, coordonnées de contact renseignées.", "C"),
])
